<form method="post" action="index.php?page=logout">
	<button type="submit">LOGOUT</button>
</form>
<h1>HOMEPAGE</h1>
<h2>Bonjour <?php echo htmlentities($_SESSION['login']); ?></h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum ut rerum voluptate eaque dolor odit, sit porro cumque quas, dolorem minus. Nulla ab at obcaecati! Facere perspiciatis laboriosam ipsum aliquid?</p>
<hr/>