
<h2>LOGIN</h2>
=======
<h2>Connexion</h2>

<div style="background-color:red;"><?php echo implode('<br/>', $errors) ?></div>
<form method='post' action='index.php?page=login'>
	<label for='pseudo'>Pseudonyme : </label><input type='text' name='pseudo' value="<?php echo htmlentities($pseudo); ?>" id='pseudo' required />
	<label for='mdp'>Mot de passe : </label><input type='password' name='mdp' value="" id='mdp' required />
	<button type='submit'>LOGIN</button>
</form>