</div>
<nav class="navbar navbar-fixed-top navbar-inverse">
<!--Padding-top de 50px minimum sur le body pour compenser le navbar-fixed-top (navbar height= 50px)-->
	<div class="container">
		<div class="navbar-header">
			<a href="?page=accueil" class="navbar-brand"><img src='' alt="logo"/></a>
		</div>
		<ul class="nav navbar-nav navbar-right">
			<li><a href="?page=accueil" class="navbar-link">Accueil</a></li>
			<li><a href="?page=login" class="navbar-link">Log In</a></li>
			<li><a href="?page=register" class="navbar-link">Register</a></li>
		</ul>
	</div>
</nav>
<div class="container">