</div>
<nav class="navbar navbar-inverse">
<!--Padding-top de 50px minimum sur le body pour compenser le navbar-fixed-top (navbar height= 50px)-->
	<div class="container">
		<div class="navbar-header">
			<a href="?page=accueil" class="navbar-brand"><img src='' alt="Logo"/></a>
		</div>
		<ul class="nav navbar-nav navbar-right">
			<li><a href="index.php?page=tchat">Bonjour <?php echo htmlentities($_SESSION['login']); ?></a></li>
			<li><a href="?page=logout" class="navbar-link">Se déconnecter</a></li>
		</ul>
	</div>
</nav>
<div class="container">