<nav>
  <ul class="pagination">
    <li>
      <a href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li><a href="?page=accueil&amp;p=10&amp;o=0">1</a></li>
    <li><a href="?page=accueil&amp;p=10&amp;o=10">2</a></li>
    <li><a href="?page=accueil&amp;p=10&amp;o=20">3</a></li>
    <li><a href="?page=accueil&amp;p=10&amp;o=30">4</a></li>
    <li><a href="?page=accueil&amp;p=10&amp;o=40">5</a></li>
    <li>
      <a href="" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>