<h2>Enregistrement</h2>
<div><?=implode('<br/>', $errors)?></div>
<form method='post' action='index.php?page=register'>
	<label for='pseudo'>Pseudonyme (4 caractères minimum) : </label><input type='text' name='pseudo' value="<?php echo htmlentities($pseudo); ?>" id='pseudo'  />
	<fieldset>
		<legend>Avatar</legend>
		<label for='source'>Source</label>
		<input type='file' name='avatar' id='source' />
		<label for='url'>ou URL</label>
		<input type='url' name='avatar' id='url' class='form-control' />
	</fieldset>
	<label for='mdp'>Mot de passe (6 caractères minimum) : </label><input type='password' name='mdp1' value="" id='mdp' /><br>
	<label for='mdp2'>Vérification mot de passe : </label><input type='password' name='mdp2' value="" id='mdp2' /><br>
	<button type='submit'>Envoyer</button>
</form>