<h2>REGISTER</h2>
<div style="background-color:red;"><?php echo implode('<br/>', $errors) ?></div>
<form method='post' action='index.php?page=register'>
	<label for='pseudo'>Pseudonyme (4 caractères minimum) : </label><input type='text' name='pseudo' value="<?php echo htmlentities($pseudo); ?>" id='pseudo'  />
	<fieldset>
		<legend>Avatar</legend>
		<label for='source'>Source</label>
		<input type='file' name='avatar_source' id='source' />
		<label for='url'>ou URL</label>
		<input type='url' name='avatar_url' id='url' class='form-control' />
	</fieldset>
	<label for='mdp'>Mot de passe (6 caractères minimum) : </label><input type='password' name='mdp' value="" id='mdp' />
	<label for='mdp2'>Vérification mot de passe : </label><input type='password' name='mdp2' value="" id='mdp2' />
	<button type='submit'>REGISTER</button>
</form>