<!DOCTYPE html>

<html lang="fr">

	<head>

		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><?php echo $titre; ?></title>		
		<link rel="stylesheet" href="public/styles/reset.css">
		<link rel="stylesheet" href="public/styles/bootstrap.min.css">
		<link rel="stylesheet" href="public/styles/font-awesome/css/font-awesome.min.css">	
		<link rel="stylesheet/less" href="public/styles/style.less">	
		<script src="//cdnjs.cloudflare.com/ajax/libs/less.js/2.5.3/less.min.js"></script>	
		<script type="text/javascript" src="public/scripts/prefixfree.min.js"></script>						
		<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->			

	</head>

	<body>

		<div class="container">
			<?php require('apps/menu.php'); ?>		
			<?php require('apps/content.php'); ?>
			<?php require('apps/footer.php'); ?>
		</div>

		<script src="public/scripts/jquery-2.1.4.min.js"></script>
		<script src="public/scripts/bootstrap.min.js"></script>
		<script src="public/scripts/script.js"></script>

	</body>

</html>