<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<script src="public/scripts/jquery-2.1.4.min.js"></script>
	<script src="public/scripts/prefixfree.min.js"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
	<link rel="stylesheet" href="public/styles/stylesheet.css">
	<script src="public/scripts/script.js"></script>
	<title><?php echo $titre; ?></title>
</head>
<body>
	<div class="container">
		<?php require('apps/menu.php'); ?>
		<?php require('apps/header.php'); ?>
		<?php require('apps/content.php'); ?>
		<?php require('apps/footer.php'); ?>
	</div>
</body>
</html>